## Part 1: Explore the Data

Import the data and use Pandas to learn more about the dataset.

In [104]:
import pandas as pd

df = pd.read_csv('Resources/client_dataset.csv')
df.head()

first      last                    job               phone  \
0     Donald   Harding           Immunologist  793-904-7725x39308   
1    Tiffany     Myers        Music therapist    201.442.4543x942   
2    Shannon    Watson           Immunologist   687.737.9424x8503   
3     Nathan     Baker  Accounting technician    827-788-8123x012   
4  Christina  Schwartz           Chiropractor        265-829-3643   

                                 email  client_id  order_id  order_date  \
0     harding.donald.7185@sullivan.com      58515   8953482  2023-04-28   
1    myers.t.6537@ferguson-johnson.net      37609   8069089  2023-05-19   
2                swatson8146@payne.net      57113   1902144  2023-01-29   
3               bakernathan@benson.com      46554   9031802  2023-04-25   
4  christinaschwartz9252@mcconnell.com      92089   1322274  2023-05-28   

   order_week  order_year         item_id     category         subcategory  \
0          17        2023  EUD29711-63-6U        decor            wall art   
1          20        2023  XDA18116-89-4A  consumables                pens   
2           4        2023  ABE59463-05-7E     software  project management   
3          17        2023  ZMM00836-65-0C  consumables                pens   
4          21        2023  BZX55559-12-3X  consumables                misc   

   unit_price  unit_cost  unit_weight  qty  line_number  
0     1096.80     762.71         7.50  105            1  
1       24.95      15.09         1.49   21            0  
2       13.52       7.86         1.68   39            6  
3       36.42      24.85         1.23   29            3  
4      195.10     108.17        46.43   20            1

In [105]:
# View the column names in the data
df.columns

Index(['first', 'last', 'job', 'phone', 'email', 'client_id', 'order_id',
       'order_date', 'order_week', 'order_year', 'item_id', 'category',
       'subcategory', 'unit_price', 'unit_cost', 'unit_weight', 'qty',
       'line_number'],
      dtype='object')

In [198]:
# Use the describe function to gather some basic statistics
df.describe()

client_id      order_id    order_week    order_year    unit_price  \
count  54639.000000  5.463900e+04  54639.000000  54639.000000  54639.000000   
mean   54837.869416  5.470190e+06     11.359139   2022.993064    136.267207   
std    25487.438231  2.599807e+06      7.023499      0.082997    183.873135   
min    10033.000000  1.000886e+06      1.000000   2022.000000      0.010000   
25%    33593.000000  3.196372e+06      6.000000   2023.000000     20.800000   
50%    53305.000000  5.496966e+06     11.000000   2023.000000     68.310000   
75%    78498.000000  7.733869e+06     17.000000   2023.000000    173.160000   
max    99984.000000  9.998480e+06     52.000000   2023.000000   1396.230000   

          unit_cost   unit_weight           qty   line_number  line_subtotal  \
count  54639.000000  54639.000000  5.463900e+04  54639.000000   5.463900e+04   
mean      99.446073      5.004116  5.702646e+02      2.979667   7.710286e+04   
std      133.164267      5.326599  1.879552e+04      2.436320   2.881926e+06   
min        0.010000      0.000000  0.000000e+00      0.000000   0.000000e+00   
25%       14.840000      1.450000  3.200000e+01      1.000000   1.132950e+03   
50%       49.890000      3.240000  6.800000e+01      3.000000   4.629440e+03   
75%      125.570000      6.890000  1.700000e+02      5.000000   1.736913e+04   
max      846.270000     46.430000  3.958244e+06      9.000000   5.844743e+08   

       total_weight  shipping_price    line_price     line_cost   line_profit  
count  5.463900e+04    5.463900e+04  5.463900e+04  5.463900e+04  5.463900e+04  
mean   2.487416e+03    1.742510e+04  1.032718e+05  7.387972e+04  2.939207e+04  
std    5.559430e+04    3.891595e+05  3.286505e+06  2.133294e+06  1.195291e+06  
min    0.000000e+00    0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  
25%    7.033000e+01    4.966500e+02  2.887560e+03  2.206360e+03  5.597750e+02  
50%    2.254000e+02    1.577800e+03  8.396490e+03  6.266040e+03  1.894840e+03  
75%    7.184400e+02    5.029080e+03  2.645604e+04  1.946590e+04  6.674210e+03  
max    9.009056e+06    6.306339e+07  6.412625e+08  3.987535e+08  2.425090e+08

In [197]:
# Use this space to do any additional research
# and familiarize yourself with the data.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54639 entries, 0 to 54638
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   first           54639 non-null  object 
 1   last            54639 non-null  object 
 2   job             54639 non-null  object 
 3   phone           54639 non-null  object 
 4   email           54639 non-null  object 
 5   client_id       54639 non-null  int64  
 6   order_id        54639 non-null  int64  
 7   order_date      54639 non-null  object 
 8   order_week      54639 non-null  int64  
 9   order_year      54639 non-null  int64  
 10  item_id         54639 non-null  object 
 11  category        54639 non-null  object 
 12  subcategory     54639 non-null  object 
 13  unit_price      54639 non-null  float64
 14  unit_cost       54639 non-null  float64
 15  unit_weight     54639 non-null  float64
 16  qty             54639 non-null  int64  
 17  line_number     54639 non-null 

In [107]:
# What three item categories had the most entries?
count = df["category"].value_counts()
count.head(3)

category
consumables    23538
furniture      11915
software        8400
Name: count, dtype: int64

In [108]:
# For the category with the most entries, which subcategory had the most entries?
sub_count = df["subcategory"].value_counts()
sub_count.head(1)

subcategory
bathroom supplies    6424
Name: count, dtype: int64

In [109]:
# Which five clients had the most entries in the data?
client_count = df["client_id"].value_counts()
client_count.head(5)

client_id
33615    220
66037    211
46820    209
38378    207
24741    207
Name: count, dtype: int64

In [110]:
# Which five clients had the most entries in the data?
top_clients = client_count.head(5)
top_clients

client_id
33615    220
66037    211
46820    209
38378    207
24741    207
Name: count, dtype: int64

In [111]:
# Store the client ids of those top 5 clients in a list.
# top_client_ids = top_clients['client_id'].tolist()
top_clients_id = [33615, 66037, 46820, 38378, 24741]

In [112]:
print(top_clients_id)

[33615, 66037, 46820, 38378, 24741]


In [95]:
top_df = df[['client_id', 'qty']].copy()

top_df.loc[top_df['client_id'] == 33615].head()

Empty DataFrame
Columns: [client_id, qty]
Index: []

In [92]:
# top_df = df\
#                .loc[df['client_id', 'qty']]\
#                .copy()\

top_df = df[['client_id', 'qty']].copy()
top_df.head()


people_csv.loc[people_csv['age'] == 39].head()


define if top_df["client_id"] == "33615"
retutn top_df[qty].sum
# Define a function
def shipping_price(total_weight):
    if total_weight > 50:
        return total_weight * 7
    else:
        return total_weight * 10

# "Apply" the function to the total_weight column
df["shipping_price"] = df["total_weight"].apply(shipping_price)
# df.head()

# Reference multiple columns within a DataFrame.
df[["unit_price", "unit_weight", "qty", "total_weight", "shipping_price"]].head(3)


answer = 

client_id  qty
0     58515  105
1     37609   21
2     57113   39
3     46554   29
4     92089   20

In [155]:
# How many total units (the qty column) did the client with the most entries order order?
first_client_id_list = [33615]
for first_client in first_client_id_list:
    unit_sum = round(df[df['client_id']==first_client]['qty'].sum(),2)
    print(unit_sum)

64313


## Part 2: Transform the Data
Do we know that this client spent the more money than client 66037? If not, how would we find out? Transform the data using the steps below to prepare it for analysis.

In [113]:
# Create a column that calculates the subtotal for each line using the unit_price and the qty
subtotal = df["unit_price"] * df["qty"]
df["line_subtotal"] = subtotal

# Reference multiple columns within a DataFrame.
df[["unit_price", "qty", "line_subtotal"]].head(2)

unit_price  qty  line_subtotal
0     1096.80  105      115164.00
1       24.95   21         523.95

In [114]:
df["total_weight"] = df["unit_weight"] * df["qty"]

df[["unit_weight", "qty", "total_weight"]].head()


unit_weight  qty  total_weight
0         7.50  105        787.50
1         1.49   21         31.29
2         1.68   39         65.52
3         1.23   29         35.67
4        46.43   20        928.60

In [116]:
# Create a column for shipping price.
# Assume a shipping price of $7 per pound for orders over 50 pounds and $10 per pound for items 50 pounds or under.

# Define a function
def shipping_price(total_weight):
    if total_weight > 50:
        return total_weight * 7
    else:
        return total_weight * 10

# "Apply" the function to the total_weight column
df["shipping_price"] = df["total_weight"].apply(shipping_price)
# df.head()

# Reference multiple columns within a DataFrame.
df[["unit_price", "unit_weight", "qty", "total_weight", "shipping_price"]].head(3)


unit_price  unit_weight  qty  total_weight  shipping_price
0     1096.80         7.50  105        787.50         5512.50
1       24.95         1.49   21         31.29          312.90
2       13.52         1.68   39         65.52          458.64

In [117]:
# Create a column for the total price using the subtotal and the shipping price along with a sales tax of 9.25%
# Sales tax rate
sales_tax_rate = 0.0925

# Calculate total price
# df['line_price'] = df['line_subtotal'] * (1 + sales_tax_rate) + df['shipping_price']
price = df["line_subtotal"] + df["shipping_price"]
total_price = price * .0925

df["line_price"] = price + total_price.round(2)

df[["line_subtotal", "shipping_price", "line_price"]].head(3)


line_subtotal  shipping_price  line_price
0      115164.00         5512.50   131839.08
1         523.95          312.90      914.26
2         527.28          458.64     1077.12

In [118]:
# Create a column for the cost of each line using unit cost, qty, and
# shipping price (assume the shipping cost is exactly what is charged to the client).

df["line_cost"] = df["unit_cost"] * df["qty"] + df["shipping_price"]
df.head(3)



first     last              job               phone  \
0   Donald  Harding     Immunologist  793-904-7725x39308   
1  Tiffany    Myers  Music therapist    201.442.4543x942   
2  Shannon   Watson     Immunologist   687.737.9424x8503   

                               email  client_id  order_id  order_date  \
0   harding.donald.7185@sullivan.com      58515   8953482  2023-04-28   
1  myers.t.6537@ferguson-johnson.net      37609   8069089  2023-05-19   
2              swatson8146@payne.net      57113   1902144  2023-01-29   

   order_week  order_year  ... unit_price unit_cost unit_weight  qty  \
0          17        2023  ...    1096.80    762.71        7.50  105   
1          20        2023  ...      24.95     15.09        1.49   21   
2           4        2023  ...      13.52      7.86        1.68   39   

   line_number  line_subtotal  total_weight  shipping_price  line_price  \
0            1      115164.00        787.50         5512.50   131839.08   
1            0         523.95         31.29          312.90      914.26   
2            6         527.28         65.52          458.64     1077.12   

   line_cost  
0   85597.05  
1     629.79  
2     765.18  

[3 rows x 23 columns]

In [119]:
# Create a column for the profit of each line using line cost and line price

df["line_profit"] = df["line_price"] - df["line_cost"]

df.head(3)



first     last              job               phone  \
0   Donald  Harding     Immunologist  793-904-7725x39308   
1  Tiffany    Myers  Music therapist    201.442.4543x942   
2  Shannon   Watson     Immunologist   687.737.9424x8503   

                               email  client_id  order_id  order_date  \
0   harding.donald.7185@sullivan.com      58515   8953482  2023-04-28   
1  myers.t.6537@ferguson-johnson.net      37609   8069089  2023-05-19   
2              swatson8146@payne.net      57113   1902144  2023-01-29   

   order_week  order_year  ... unit_cost unit_weight  qty  line_number  \
0          17        2023  ...    762.71        7.50  105            1   
1          20        2023  ...     15.09        1.49   21            0   
2           4        2023  ...      7.86        1.68   39            6   

   line_subtotal  total_weight  shipping_price  line_price  line_cost  \
0      115164.00        787.50         5512.50   131839.08   85597.05   
1         523.95         31.29          312.90      914.26     629.79   
2         527.28         65.52          458.64     1077.12     765.18   

   line_profit  
0     46242.03  
1       284.47  
2       311.94  

[3 rows x 24 columns]

## Part 3: Confirm your work
You have email receipts showing that the total prices for 3 orders. Confirm that your calculations match the receipts. Remember, each order has multiple lines.

Order ID 2742071 had a total price of \$152,811.89

Order ID 2173913 had a total price of \$162,388.71

Order ID 6128929 had a total price of \$923,441.25


In [136]:
# Check your work using the totals above

order_id_list = [2742071, 2173913, 6128929]
for order in order_id_list:
    order_sum = round(df[df['order_id']==order]['line_price'].sum(),2)
    print(f"Order ID {order}: Total price is ${order_sum}")

Order ID 2742071: Total price is $152811.89
Order ID 2173913: Total price is $162388.71
Order ID 6128929: Total price is $923441.25


## Part 4: Summarize and Analyze
Use the new columns with confirmed values to find the following information.

In [186]:
# How much did each of the top 5 clients by quantity spend? Check your work from Part 1 for client ids.

top_client_id_list = [33615, 66037, 46820, 38378, 24741]
for top_client in top_client_id_list:
    total_sum = round(df[df['client_id']==top_client]['line_price'].sum(),2)
    print(f"{top_client}: ${total_sum}")


33615: $8377308.52
66037: $10259514.79
46820: $9743794.36
38378: $12906550.87
24741: $82268892.02


In [190]:
# Create a summary DataFrame showing the totals for the for the top 5 clients with the following information:
# total units purchased, total shipping price, total revenue, and total profit. 

summary_df = df[['client_id', 'qty', 'shipping_price', 'line_price', 'line_cost', 'line_profit']].copy()
order_list=[]
for client_id in top_clients_id:
    order_list.append({
        "client_id": client_id
        ,"qty": summary_df[summary_df['client_id']==client_id]['qty'].sum()
        ,"shipping_price": round(summary_df[summary_df['client_id']==client_id]['shipping_price'].sum(),2)
        ,"line_price": round(summary_df[summary_df['client_id']==client_id]['line_price'].sum(),2)
        ,"line_cost": round(summary_df[summary_df['client_id']==client_id]['line_cost'].sum(),2)
        ,"line_profit": round(summary_df[summary_df['client_id']==client_id]['line_profit'].sum(),2)
        })

top_summary_df = pd.DataFrame(order_list)
top_summary_df[['client_id', 'qty', 'shipping_price', 'line_price', 'line_cost', 'line_profit']]

client_id     qty  shipping_price   line_price    line_cost  line_profit
0      33615   64313      1828984.89   8377308.52   6175313.91   2201994.61
1      66037   43018      1395151.85  10259514.79   7004482.98   3255031.81
2      46820   75768      1601448.84   9743794.36   7007191.64   2736602.72
3      38378   73667      3429455.40  12906550.87   9634720.98   3271829.89
4      24741  239862      5126448.37  82268892.02  45688899.71  36579992.31

In [180]:
top_summary_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   client_id       5 non-null      int64  
 1   qty             5 non-null      int64  
 2   shipping_price  5 non-null      float64
 3   line_price      5 non-null      float64
 4   line_cost       5 non-null      float64
 5   line_profit     5 non-null      float64
dtypes: float64(4), int64(2)
memory usage: 368.0 bytes


In [181]:
top_summerized_df = top_summary_df.copy()
top_summerized_df

client_id     qty  shipping_price   line_price    line_cost  line_profit
0      33615   64313      1828984.89   8377308.52   6175313.91   2201994.61
1      66037   43018      1395151.85  10259514.79   7004482.98   3255031.81
2      46820   75768      1601448.84   9743794.36   7007191.64   2736602.72
3      38378   73667      3429455.40  12906550.87   9634720.98   3271829.89
4      24741  239862      5126448.37  82268892.02  45688899.71  36579992.31

In [191]:
ship_to_mill = top_summerized_df["shipping_price"] / 1000000
top_summerized_df["Shipping (millions)"] = ship_to_mill

price_to_mill = top_summerized_df["line_price"] / 1000000
top_summerized_df["Total Revenue (millions)"] = price_to_mill

cost_to_mill = top_summerized_df["line_cost"] / 1000000
top_summerized_df["Total Cost (millions)"] = cost_to_mill

profit_to_mill = top_summerized_df["line_profit"] / 1000000
top_summerized_df["Total Profit (millions)"] = profit_to_mill

top_summerized_df

client_id     qty  shipping_price   line_price    line_cost  line_profit  \
0      33615   64313      1828984.89   8377308.52   6175313.91   2201994.61   
1      66037   43018      1395151.85  10259514.79   7004482.98   3255031.81   
2      46820   75768      1601448.84   9743794.36   7007191.64   2736602.72   
3      38378   73667      3429455.40  12906550.87   9634720.98   3271829.89   
4      24741  239862      5126448.37  82268892.02  45688899.71  36579992.31   

   Shipping (millions)  Total Revenue (millions)  lTotal Cost (millions)  \
0             1.828985                  8.377309                6.175314   
1             1.395152                 10.259515                7.004483   
2             1.601449                  9.743794                7.007192   
3             3.429455                 12.906551                9.634721   
4             5.126448                 82.268892               45.688900   

   Total Profit (millions)  Total Cost (millions)  
0                 2.201995               6.175314  
1                 3.255032               7.004483  
2                 2.736603               7.007192  
3                 3.271830               9.634721  
4                36.579992              45.688900

In [193]:
# Format the data and rename the columns to names suitable for presentation.
top_summerized_df.rename(columns={'client_id': 'Client Id', 'qty': 'Units'}, inplace=True)

# Define the money columns. 
# Define a function that converts a dollar amount to millions.

# Apply the currency_format_millions function to only the money columns. 

# Rename the columns to reflect the change in the money format. 

top_five_clients_df = top_summerized_df[['Client Id', 'Units', 'Shipping (millions)', 'Total Revenue (millions)', 'Total Cost (millions)', 'Total Profit (millions)']].copy()

top_five_clients_df

Client Id   Units  Shipping (millions)  Total Revenue (millions)  \
0      33615   64313             1.828985                  8.377309   
1      66037   43018             1.395152                 10.259515   
2      46820   75768             1.601449                  9.743794   
3      38378   73667             3.429455                 12.906551   
4      24741  239862             5.126448                 82.268892   

   Total Cost (millions)  Total Profit (millions)  
0               6.175314                 2.201995  
1               7.004483                 3.255032  
2               7.007192                 2.736603  
3               9.634721                 3.271830  
4              45.688900                36.579992

In [196]:

# Sort the updated data by "Total Profit (millions)" form highest to lowest and assign the sort to a new DatFrame.
top_five_clients_profit_df = top_five_clients_df.sort_values("Total Profit (millions)", ascending=False)
top_five_clients_profit_df

Client Id   Units  Shipping (millions)  Total Revenue (millions)  \
4      24741  239862             5.126448                 82.268892   
3      38378   73667             3.429455                 12.906551   
1      66037   43018             1.395152                 10.259515   
2      46820   75768             1.601449                  9.743794   
0      33615   64313             1.828985                  8.377309   

   Total Cost (millions)  Total Profit (millions)  
4              45.688900                36.579992  
3               9.634721                 3.271830  
1               7.004483                 3.255032  
2               7.007192                 2.736603  
0               6.175314                 2.201995

# Summary of Findings
Despite having the most entities in the data, Client Id 33615 had the lowest Total Profit. And the Client Ids with the lowest entries in the data, 24741 and 38378 had the highest total profit. In fact, Client Id 24741's Total Profit is ten times greater than the other 4 top Client Ids showing that <ins>Total Revenue</ins> (line_cost) and <ins>Total Price</ins>  (line_price) are more significant when it comes to a client's total profit.


# All work below was completed prior to work above as I was trying to work through various code snippet 
All work below shows my work and ways I tried to work the above code to get the results provided. After having a hard time figuring out some specific actions needed, such as define the money function, I used other ways to get to the results provided and wanted to make sure I at least got credit for trying to work through the problems using methods and function called for. 

In [157]:
# Create a summary DataFrame showing the totals for the for the top 5 clients with the following information:
# total units purchased, total shipping price, total revenue, and total profit. 

summary_df = df[['client_id', 'qty', 'shipping_price', 'line_price', 'line_cost', 'line_profit']].copy()
order_list=[]
for client_id in top_clients_id:
    order_list.append({
        "Client ID": client_id
        ,"Units": summary_df[summary_df['client_id']==client_id]['qty'].sum()
        ,"Shipping (millions)": round(summary_df[summary_df['client_id']==client_id]['shipping_price'].sum(),2)
        ,"Total Revenue (millions)": round(summary_df[summary_df['client_id']==client_id]['line_price'].sum(),2)
        ,"Total Cost (millions)": round(summary_df[summary_df['client_id']==client_id]['line_cost'].sum(),2)
        ,"Total Profit (millions)": round(summary_df[summary_df['client_id']==client_id]['line_profit'].sum(),2)
        })

top_summary_df = pd.DataFrame(order_list)
top_summary_df[['Client ID', 'Units', 'Shipping (millions)', 'Total Revenue (millions)', 'Total Cost (millions)', 'Total Profit (millions)']]

Client ID   Units  Shipping (millions)  Total Revenue (millions)  \
0      33615   64313           1828984.89                8377308.52   
1      66037   43018           1395151.85               10259514.79   
2      46820   75768           1601448.84                9743794.36   
3      38378   73667           3429455.40               12906550.87   
4      24741  239862           5126448.37               82268892.02   

   Total Cost (millions)  Total Profit (millions)  
0             6175313.91               2201994.61  
1             7004482.98               3255031.81  
2             7007191.64               2736602.72  
3             9634720.98               3271829.89  
4            45688899.71              36579992.31

In [ ]:
# Create a summary DataFrame showing the totals for the for the top 5 clients with the following information:
# total units purchased, total shipping price, total revenue, and total profit. 

summary_df = df[['client_id', 'qty', 'shipping_price', 'line_price', 'line_cost', 'line_profit']].copy()
order_list=[]
for client_id in top_clients_id:
    order_list.append({
        "Client ID": client_id
        ,"Units": summary_df[summary_df['client_id']==client_id]['qty'].sum()
        ,"Shipping (millions)": round(summary_df[summary_df['client_id']==client_id]['shipping_price'].sum(),2)
        ,"Total Revenue (millions)": round(summary_df[summary_df['client_id']==client_id]['line_price'].sum(),2)
        ,"Total Cost (millions)": round(summary_df[summary_df['client_id']==client_id]['line_cost'].sum(),2)
        ,"Total Profit (millions)": round(summary_df[summary_df['client_id']==client_id]['line_profit'].sum(),2)
        })

top_summary_df = pd.DataFrame(order_list)
top_summary_df[['Client ID', 'Units', 'Shipping (millions)', 'Total Revenue (millions)', 'Total Cost (millions)', 'Total Profit (millions)']]

Client ID   Units  Shipping (millions)  Total Revenue (millions)  \
0      33615   64313           1828984.89                8377308.52   
1      66037   43018           1395151.85               10259514.79   
2      46820   75768           1601448.84                9743794.36   
3      38378   73667           3429455.40               12906550.87   
4      24741  239862           5126448.37               82268892.02   

   Total Cost (millions)  Total Profit (millions)  
0             6175313.91               2201994.61  
1             7004482.98               3255031.81  
2             7007191.64               2736602.72  
3             9634720.98               3271829.89  
4            45688899.71              36579992.31

In [158]:
top_five_df = top_summary_df.copy()
top_five_df.head()

Client ID   Units  Shipping (millions)  Total Revenue (millions)  \
0      33615   64313           1828984.89                8377308.52   
1      66037   43018           1395151.85               10259514.79   
2      46820   75768           1601448.84                9743794.36   
3      38378   73667           3429455.40               12906550.87   
4      24741  239862           5126448.37               82268892.02   

   Total Cost (millions)  Total Profit (millions)  
0             6175313.91               2201994.61  
1             7004482.98               3255031.81  
2             7007191.64               2736602.72  
3             9634720.98               3271829.89  
4            45688899.71              36579992.31

In [ ]:
to_mill = top_five_df["Shipping (millions)"] / 1000000
top_five_df["mill"] = to_mill

top_five_df

Client ID   Units  Shipping (millions)  Total Revenue (millions)  \
0      33615   64313           1828984.89                8377308.52   
1      66037   43018           1395151.85               10259514.79   
2      46820   75768           1601448.84                9743794.36   
3      38378   73667           3429455.40               12906550.87   
4      24741  239862           5126448.37               82268892.02   

   Total Cost (millions)  Total Profit (millions)      mill  
0             6175313.91               2201994.61  1.828985  
1             7004482.98               3255031.81  1.395152  
2             7007191.64               2736602.72  1.601449  
3             9634720.98               3271829.89  3.429455  
4            45688899.71              36579992.31  5.126448

In [ ]:
def apply_complex_function(x):
    top_five_df["Value"] / 1000000
    return complex_function(x['col1'], x['col2'])
df['col1'] = df.apply(apply_complex_function, axis=1)

def apply_complex_function(x):
    return complex_function(x['col1'], x['col2'])
df['col1'] = df.apply(apply_complex_function, axis=1)

In [ ]:
def to_million
    top_five_df["Value"] = top_five_df["Value"] / 1000000
    top_five_df["Value"] = top_five_df["Value"].map("${:,.2f}M".format)

In [174]:
def to_million(dollarvalue):
    return dollarvalue / 1000000

top_five_df['Shipping (millions'] = top_five_df['Shipping (millions'].apply(to_million)
    
top_five_df.head()

KeyError: 'Shipping (millions'

In [172]:
top_five_df['Shipping (millions)']

def to_million(x):
    df["Value"] = df["Value"] / 1000000
    df["Value"] = df["Value"].map("${:,.2f}M".format)

top_five_df['Shipping (millions'] = top_five_df['Shipping (millions'].apply(to_million)

KeyError: 'Shipping (millions'

In [170]:
top_five_df.head()

Client ID   Units  Shipping (millions)  Total Revenue (millions)  \
0      33615   64313           1828984.89                8377308.52   
1      66037   43018           1395151.85               10259514.79   
2      46820   75768           1601448.84                9743794.36   
3      38378   73667           3429455.40               12906550.87   
4      24741  239862           5126448.37               82268892.02   

   Total Cost (millions)  Total Profit (millions)  
0             6175313.91               2201994.61  
1             7004482.98               3255031.81  
2             7007191.64               2736602.72  
3             9634720.98               3271829.89  
4            45688899.71              36579992.31

In [18]:
# Format the data and rename the columns to names suitable for presentation.

# Define the money columns. 


# Define a function that converts a dollar amount to millions.
city_dataframe['Population'] = city_dataframe['Population'] / 1000000


# format the values as currency in millions
df["Value"] = df["Value"] / 1000000
df["Value"] = df["Value"].map("${:,.2f}M".format)

# Apply the currency_format_millions function to only the money columns. 


# Rename the columns to reflect the change in the money format. 




Client ID   Units  Shipping (millions)  Total Revenue (millions)  \
0      33615   64313             1.828985                  8.377309   
1      66037   43018             1.395152                 10.259515   
2      46820   75768             1.601449                  9.743794   
3      38378   73667             3.429455                 12.906551   
4      24741  239862             5.126448                 82.268892   

   Total Cost (millions)  Total Profit (millions)  
0               6.175314                 2.201995  
1               7.004483                 3.255032  
2               7.007192                 2.736603  
3               9.634721                 3.271830  
4              45.688900                36.579992

In [ ]:
# Format the data and rename the columns to names suitable for presentation.

# Define the money columns. 


# Define a function that converts a dollar amount to millions.
# format the values as currency in thousands
df["Value"] = df["Value"] / 1000
df["Value"] = df["Value"].map("${:,.0f}K".format)


# format the values as currency in millions
df["Value"] = df["Value"] / 1000000
df["Value"] = df["Value"].map("${:,.2f}M".format)

# Apply the currency_format_millions function to only the money columns. 


# Rename the columns to reflect the change in the money format. 




Client ID   Units  Shipping (millions)  Total Revenue (millions)  \
0      33615   64313             1.828985                  8.377309   
1      66037   43018             1.395152                 10.259515   
2      46820   75768             1.601449                  9.743794   
3      38378   73667             3.429455                 12.906551   
4      24741  239862             5.126448                 82.268892   

   Total Cost (millions)  Total Profit (millions)  
0               6.175314                 2.201995  
1               7.004483                 3.255032  
2               7.007192                 2.736603  
3               9.634721                 3.271830  
4              45.688900                36.579992

In [ ]:
# df = df.astype({"order_id": str}, errors='raise') 
# df = df.astype({"order_id": str})
# df["order_id"].dtype
# df.info()

# df = df[df["order_id"].str.contains("2742021")] 

# top_client_df = df.loc[df["client_id"] == "33615"]
# top_client_df.reset_index(drop=True, inplace=True)
# top_client_df.head()

# Set the index as the 'first_name' column
# people_csv.set_index(people_csv['first_name'], inplace=True)
# people_csv.head()
